//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommercialCompany.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CommercialCompanyEntities : DbContext
    {
        public CommercialCompanyEntities()
            : base("name=CommercialCompanyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<clients> clients { get; set; }
        public virtual DbSet<colors> colors { get; set; }
        public virtual DbSet<contracts> contracts { get; set; }
        public virtual DbSet<dealers> dealers { get; set; }
        public virtual DbSet<models> models { get; set; }
        public virtual DbSet<upholstery> upholstery { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
