//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommercialCompany.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class contracts
    {
        public int contract_number { get; set; }
        public int client_id { get; set; }
        public int model_id { get; set; }
        public System.DateTime purchase_date { get; set; }
        public bool status { get; set; }
    
        public virtual clients clients { get; set; }
        public virtual models models { get; set; }
    }
}
