//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommercialCompany.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class models
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public models()
        {
            this.contracts = new HashSet<contracts>();
            this.dealers = new HashSet<dealers>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int color_id { get; set; }
        public int upholstery_id { get; set; }
        public int horsepower { get; set; }
        public int doors_number { get; set; }
        public bool transmission { get; set; }
        public int release_year { get; set; }
        public double model_price { get; set; }
        public double preparation_price { get; set; }
        public double transport_price { get; set; }
    
        public virtual colors colors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contracts> contracts { get; set; }
        public virtual upholstery upholstery { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dealers> dealers { get; set; }
    }
}
